### ISSUE TITLE
Update to v4.2.2 or latest 

### ISSUE THREAD

**Issue by alexcastillo** [resin-io-projects/resin-wifi-connect-api#3]
Hi @majorz,

Great job with this example project!

I was able to get it partially working but I found a few bugs:
- Portal sometimes only shows 1 SSID or none 
- Reopen access point when connection lost - https://github.com/balena-io/wifi-connect/issues/165
- Connecting via AP doesn't update wifi credentials - https://github.com/balena-os/meta-balena/issues/1376

Do you know if these issues are fixed in the latest version (currently on v4.2.2)?

I tried pointing the Dockerfile to v4.2.2 but got some D-Bus related errors preventing the AP to start. Any chance you can update this repo to work with v4.2.2?

Thanks!

**Comment by majorz** [comment]
The issue with 1 SSID or none should be this one: https://github.com/balena-io/wifi-connect/issues/206 We need to improve our scanning mechanisms.

What device type are you using? Some devices have issues with their drivers and which could lead to none SSIDs to be shown.

For the second issue you face, I should have made the API example here a single container application, and use wifi-connect as a subprocess to the web application. If it is handled as a subprocess then it is much easier to relaunch wifi-connect or kill it if needed. I should probably rework this indeed.

The third issue is currently worked on meta-balena and will be fixed in one of the next releases. Is it that you have a connection profile specified on the boot partition in /mnt/boot/system-connection folder which interferes with the one you create through wifi-connect?

**Comment by alexcastillo** [comment]
Thank you for the context, Zahari.

I was actually able to update this repo to use v4.2.2. It required some fixes on the UI since the API contract changed from 4.1.1 to 4.2.2 (/ssids -> /networks etc...)

1) The first issue doesn't seem to be happening anymore for me. I'll let you know if it happens again.
2) Do you have an example on how to launch wifi-connect as a subprocess?
3) This is great news, is there a tentative estimate you can provide for the next release containing the fix? I was able to override the connection profile one or two times, but now I'm not able to anymore. It appears the issue is intermittent, is that right?

**Comment by majorz** [comment]
@alexcastillo I updated the project to latest WiFi Connect. Implemented it as a single-container application. I still need to connected the stdout of wifi-connect to the web application though. I am going to close this issue now, since we have the base ready. And I am going to ping you on your support ticket so that we continue the discussion on the other issues there, since they are not related to this ticket in particular.
